apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-backend
  template:
    metadata:
      labels:
        app: news-backend
    spec:
      containers:
        - name: news-backend
          image: your-dockerhub-username/news-backend
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: news-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
