// actions/types.js

// News actions
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
export const ADD_REAL_TIME_NEWS = 'ADD_REAL_TIME_NEWS';
export const SET_TRENDING_NEWS = 'SET_TRENDING_NEWS';
export const UPDATE_NEWS_VIEW = 'UPDATE_NEWS_VIEW';

// Category actions
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SUBSCRIBE_TO_CATEGORY = 'SUBSCRIBE_TO_CATEGORY';
export const UNSUBSCRIBE_FROM_CATEGORY = 'UNSUBSCRIBE_FROM_CATEGORY';

// UI actions
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_THEME = 'SET_THEME';
export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';
export const SET_LOADING = 'SET_LOADING';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';